# Generated by Django 4.2.7 on 2026-01-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('has_iot_device', models.BooleanField(default=False, help_text='Whether this room has an IoT device connected')),
                ('iot_device_id', models.CharField(blank=True, help_text='Firebase device ID', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='OccupancyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_data', models.JSONField(blank=True, default=dict, help_text='Raw sensor data from IoT device')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_history', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Occupancy Data',
                'verbose_name_plural': 'Occupancy Data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
